/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_appypapy_lipreader_FeatureExtractor */

#ifndef _Included_com_android_appypapy_lipreader_FeatureExtractor
#define _Included_com_android_appypapy_lipreader_FeatureExtractor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_appypapy_lipreader_FeatureExtractor
 * Method:    nativeCreateObject
 * Signature: (Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_com_android_appypapy_lipreader_FeatureExtractor_nativeCreateObject
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_android_appypapy_lipreader_FeatureExtractor
 * Method:    nativeDestroyObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_android_appypapy_lipreader_FeatureExtractor_nativeDestroyObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_android_appypapy_lipreader_FeatureExtractor
 * Method:    nativeDetect
 * Signature: (JJJ[I)V
 */
JNIEXPORT void JNICALL Java_com_android_appypapy_lipreader_FeatureExtractor_nativeDetect
  (JNIEnv *, jclass, jlong, jlong, jlong, jintArray);

#ifdef __cplusplus
}
#endif
#endif
